### ISSUE TITLE
Manual for use your code.

### ISSUE THREAD

**Issue by jfg** [mohierf/GlpiFront#1]
Hi !

Do you have a manual for installation ?

I have modify the file glpi_connection.js with my parameters but the connexion don't work...

Thanks

**Comment by mohierf** [comment]
Hi,
please note that this repo is a simple moke-up ... I jsut pushed very recent modifications to improve URL building. Check with your browser console that the URL is well formed

**Comment by jfg** [comment]
Hi,

Thanks for your answer.

I will follow your update. And hope you can do an installation and setup procedure with the prerequisites.

Thank you.
